FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Invalog Api

Invalog API for front end developers.

## Questions Collection [/items]

### List All Items [GET]

+ Response 200 (application/json)

        [
            {
                "item": "Table",
                "published_at": "2015-08-05T08:40:51.620Z",
                "room": "Living Room",
                "category":"furniture",
                "quantity": 1,
                "make": "Ikea",
                "model": "Alex",
                "serial": "0203030555",
                "purchase_date": "2014-08-05",
                "purchase_store": "Ikea",
                "unit_value": "35000",
                "condition": "New"
            }
        ]

### Create a New Item [POST]

You may create your own item using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            
            "item": "Lamp",
            "room": "Bed Room",
            "category":"furniture",
            "quantity": 1,
            "make": "Homes",
            "model": "Homes",
            "serial": "495009",
            "purchase_date": "2015-09-15",
            "purchase_store": "Walmart",
            "unit_value": "2500",
            "condition": "New"
        }

+ Response 201 (application/json)

    + Headers

            Location: /items/2

    + Body

            {
                "item": "Lamp",
                "published_at": "2015-08-05T08:40:51.620Z",
                "room": "Bed Room",
                "category":"furniture",
                "quantity": 1,
                "make": "Homes",
                "model": "Homes",
                "serial": "495009",
                "purchase_date": "2015-09-15",
                "purchase_store": "Walmart",
                "unit_value": "2500",
                "condition": "New"
            }
